[package]
name = "cargo-release"
description = "Cargo subcommand for you to smooth your release process."
version = "0.21.1"
license = "MIT OR Apache-2.0"
repository = "https://github.com/crate-ci/cargo-release"
readme = "README.md"
categories = ["development-tools::cargo-plugins"]
keywords = ["cargo"]
edition = "2021"
rust-version = "1.60.0"  # MSRV
include = [
  "src/**/*",
  "Cargo.toml",
  "Cargo.lock",
  "LICENSE*",
  "README.md",
  "examples/**/*"
]

[package.metadata.release]
pre-release-replacements = [
  {file="README.md", search="Current release: [a-z0-9\\.-]+", replace="Current release: {{version}}"} ,
  {file="CHANGELOG.md", search="Unreleased", replace="{{version}}", min=1},
  {file="CHANGELOG.md", search="\\.\\.\\.HEAD", replace="...{{tag_name}}", exactly=1},
  {file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}", min=1},
  {file="CHANGELOG.md", search="<!-- next-header -->", replace="<!-- next-header -->\n## [Unreleased] - ReleaseDate\n", exactly=1},
  {file="CHANGELOG.md", search="<!-- next-url -->", replace="<!-- next-url -->\n[Unreleased]: https://github.com/crate-ci/cargo-release/compare/{{tag_name}}...HEAD", exactly=1},
]

[dependencies]
cargo_metadata = "0.15"
crates-index = "0.18"
# Enabling the feature for `crates-index`
git2 = { version = "0.14.2", features = ["vendored-libgit2"], default-features = false }
toml_edit = { version = "0.14.3", features = ["easy"] }
serde = { version = "1.0", features = ["derive"] }
semver = "1.0"
quick-error = "2.0"
regex = "1.6"
bstr = "0.2.17"
termcolor = "1.0"
maplit = "1.0"
indexmap = "1.9"
time = { version = "0.3", features = ["formatting", "macros"] }
dirs-next = "2.0"
ignore = "0.4"
difflib = "0.4"
itertools = "0.10"
once_cell = "1.13.1"
clap = "3.2"
clap-cargo = { version = "0.9", features = ["cargo_metadata"] }
log = "0.4"
env_logger = "0.9"

[dev-dependencies]
assert_fs = "1.0"
predicates = "2.1"
